config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "books#index"
    resources :books do
        resources :reviews
    end
    resource :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
    #don’t have to make any database changes because the reviews table already has a book_id column so relationship is already defined in the database
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    
    def show
        @id = params[:id]
        @book = Book.find(@id)
    end
    
    def new
        @book = Book.new
        #gives us form and unsaved instance of book 
    end
    
    def create
        #saves the new book to the database
        Book.create(book_params)
        redirect_to books_path
    end
    
    def edit
        @book = Book.find(params[:id])
    end
    
    def update
        book = Book.find(params[:id])
        book.update(book_params)
        redirect_to books_path
    end
    
    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end
    
    def book_params
       
        
        params.require(:book).permit(:title, :author, :price_cents, :quantity, :description)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @book = Book.find(params[:book_id])
        @review = @book.reviews.build
    end
    
    def create
        book = Book.find(params[:book_id])
        book.reviews.create(review_params)
        redirect_to book_path(book)
    end
    
    def review_params
        #Strong parameters forces us to explcitly state what attributes can be set to prevent malicious data from entering our applications
        permitted_params = params.require(:review).permit(:body)
        permitted_params.merge(user_id: session[:user_id])
        #require a review hash, allow a body attribute within this that we can add to a new review
        #params otherwise has a bunch of data we don't want to deal with right now 
        
    end
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        #empty method is okay because Rails renders new.html.erb by default unless you tell it otherwise
    end
    
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            flash[:notice] = "Welcome back, #{user.username}!"
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:alert] = "Your username or password is invalid."
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Bye I guess"
        redirect_to root_path
    end
    
    def show
        redirect_to new_session_path
    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
    <ul>
        <li>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </li>
        <li>
            <%= f.label :author %>
            <%= f.text_field :author %>
        </li>
        <li>
            <%= f.label :price_cents %>
            <%= f.number_field :price_cents %>
        </li>
        <li>
            <%= f.label :quantity %>
            <%= f.number_field :quantity %>
            </li>
        <li>
            <%= f.label :description %>
            <%= f.text_area :description %>
        </li>
    </ul>
<%= f.submit(class: "button") %>
<% end %>
<% end %>

app/views/books/index.html.erb
<h1>Welcome to the Bookstore</h1>
<h3>We Got Books and Games</h3>


<ul>
    <% @books.each do |book| %>
        <li><%= link_to(book.title, book_path(book)) %> by <%= book.author %></li>
    <% end %>
    
    <%= link_to("Add a book", new_book_path, class:"button") %>
    
</ul>

app/views/books/new.html.erb
<%= form_for(@book) do |f| %>
<%# this one line creates a form that is submitted as a PATCH/PUT request to the app's server%->
    <ul>
        <li>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </li>
        <li>
            <%= f.label :author %>
            <%= f.text_field :author %>
        </li>
        <li>
            <%= f.label :price_cents %>
            <%= f.number_field :price_cents %>
        </li>
        <li>
            <%= f.label :quantity %>
            <%= f.number_field :quantity %>
            </li>
        <li>
            <%= f.label :description %>
            <%= f.text_area :description %>
        </li>
    </ul>
<%= f.submit(class: "button") %>

<% end %>

app/views/books/show.html.erb
<d1>
    <dt>Id</dt>
    <dd><%= @book.id %></dd>
    
    <dt>Title</dt>
    <dd><%= @book.title %></dd>
    
    <dt>Author</dt>
    <dd><%= @book.author %></dd>

    <dt>Price</dt>
    <dd><%= number_to_currency(@book.price_cents/100.0 ) %></dd>

    <dt>Quantity</dt>
    <dd><%= @book.quantity %></dd>
    
    <dt>Description</dt>
    <dd><%= @book.description %></dd>
    
     <p> Number of reviews: <%= @book.reviews.count %> </p>
    
    <ul>  
    <% @book.reviews.each do |review| %>
        <% if(review.user.present?) %>
        <li><%= review.user.username %> - <%= review.body %></li>
        <% else %>
        <li><%= review.body %></li>
        <% end %>
    <% end %>
    </ul>
    
    <%= link_to "Edit Book", edit_book_path(@book), class: "button" %>
    
    <%= link_to "Add a Review", new_book_review_path(@book), class: "button" %>
    <%= button_to("Delete Book", book_path(@book), method: :delete, class: "button danger") %>
</d1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      
      <div class="navigation">
          <div class="left">
          
          </div>
          
        <div class="center">
            <%= link_to "My Super Rad Bookstore", root_path %>
        </div>

        <div class="right">
            <% if session[:user_id].present? %>
                <%= link_to "Log Out", session_path, method: :delete %>
            <% else %>
                
            <%= link_to "Log In", new_session_path %>
            <% end %>
        </div>
      </div>

      
      <% if flash[:notice] %>
        <p class="notice"> <%= flash[:notice] %> </p>
      <% end %>

      <% if flash[:alert] %>
        <p class="alert"> <%= flash[:alert] %> </p>
      <% end %>

      
      <div class="container">
        <%= yield %>
      </div>

  </body>
</html>

app/views/reviews/new.html.erb
<h1> New Review for <%= @book.title %> </h1>

<%= form_for([@book, @review]) do |f| %>
    <ul>
        <li> 
            <%= f.label :body %>
            <%= f.text_field :body %>
        </li>

    </ul>

<%= f.submit(class: "button") %>
<% end %>